export const BrasilCases = [
    {
        image: '/cases/brasil/somos-agua.png',
        project: 'PROJETO SOMOS ÁGUA',
        client: 'Prefeitura, Secretaria de Meio Ambiente e Secretaria de Assistência Social de Rio Verde (Goiás).',
        where: 'Goiás',
        when: '2019',
    },
    {
        image: '/cases/brasil/a-agua-que-falta.png',
        project: 'A Água que Falta',
        client: 'Pacto Global da ONU Brasil, Ambev, Aegea, AESabesp, Enauta, CEBDS e Arcelor Mittal',
        where: 'Brasil',
        when: '2018',
    },
    {
        image: '/cases/brasil/desafios-globais.png',
        project: 'Desafios globais e uma visão sistêmica sobre a água para o alcance da Agenda 2030 ',
        client: 'AESabesp',
        where: 'Rio de Janeiro, Fernando de Noronha, Recife, Niterói, São Paulo',
        when: '2019',
    },
    {
        image: '/cases/brasil/oceano-inovacao-e-sustentabilidade.png',
        project: 'Oceano: Inovação e Sustentabilidade',
        client: 'Pacto Global Brasil e Enauta',
        where: '-',
        when: '2019',
    },
    {
        image: '/cases/brasil/workshop-compromisso-empresarial.png',
        project: 'Workshop: Compromisso Empresarial de Segurança Hídrica',
        client: 'CEBDS (Conselho Empresarial Brasileiro para o Desenvolvimento Sustentável) e Arcelor Mittal',
        where: 'Rio de Janeiro',
        when: '2019',
    },
    {
        image: '/cases/brasil/wil-brasil.png',
        project: 'WIL Brasil',
        client: 'WIL Brasil, principais apoiadores: BRK Soluções Ambientais e Purificadores Europa',
        where: 'SP, Recife',
        when: '2018 a 2021',
    },
    {
        image: '/cases/brasil/ame.png',
        project: 'Acqua Mater Experience',
        client: '-',
        where: 'Rio de Janeiro',
        when: '2020',
    },
    {
        image: '/cases/brasil/profundezas.png',
        project: 'Profundezas',
        client: 'É Realizações Editora',
        where: '-',
        when: '2017',
    },
    
];

export const WorldCases = [
    {
        image: '/cases/mundo/conferencia-da-onu.png',
        project: 'Conferência do Oceano da ONU',
        client: 'Pacto Global da ONU, Sustainable Ocean Alliance, CEIIA, Nova School of Business Economics, Prefeitura de Cascais, Departamento de Estado dos Estados Unidos, Venture Well,Conferência do Oceano da ONU, Grupo Prada, Comissão Europeia, Coalisão EU4Ocean e COI-UNESCO',
        where: 'Lisboa',
        when: '2022',
    },
    {
        image: '/cases/mundo/europa.png',
        project: 'Europa 2019-2022',
        client: 'Galp Energia, CEIIA, UN Global Compact / Sustainable Ocean Business Action Platform, Oceans & Flow, Campus Party, SOA Hub Portugal, Sciaena, Ocean Hub Portugal / Sustainable Ocean Alliance, APDA - Associação Portuguesa de Distribuição e Drenagem de Águas, Rinascita Digitale, The Nature Coaching Academy',
        where: 'Portugal, Itália',
        when: '2019-2022',
    },
    {
        image: '/cases/mundo/forum-da-inovacao-e-da-juventude.png',
        project: 'Fórum da Inovação e da Juventude',
        client: 'Pacto Global da ONU, Sustainable Ocean Alliance, CEIIA, Nova School of Business Economics, Prefeitura de Cascais.',
        where: ' -',
        when: '2022',
    },
    {
        image: '/cases/mundo/gist-ocean-series.png',
        project: 'GIST – Oceans Series Startup Pitch Showcase for Innovative Water Solutions',
        client: 'Departamento de Estado dos Estados Unidos, Venture Well',
        where: 'Estados Unidos',
        when: '-',
    },
    {
        image: '/cases/mundo/oceano-une-jovens.png',
        project: 'O Oceano une os jovens – nossa contribuição para a Conferência do Oceano da ONU 2022 e para a Década da Ciência Oceânica para o Desenvolvimento Sustentável',
        client: 'Conferência do Oceano da ONU',
        where: 'Estados Unidos',
        when: '2021-2030',
    },
    {
        image: '/cases/mundo/se-beyond.png',
        project: 'Sea Beyond – Second Edition',
        client: 'Grupo Prada e COI-UNESCO',
        where: '-',
        when: '-',
    },
    {
        image: '/cases/mundo/arena-oceano.png',
        project: 'Arena Oceano',
        client: 'Pacto Global da ONU Brasil',
        where: '-',
        when: '-',
    },
    {
        image: '/cases/mundo/ocean-literacy-dialogues.png',
        project: 'Ocean Literacy Dialogues',
        client: 'COI-UNESCO, Comissão Europeia e Coalisão EU4Ocean.',
        where: 'Europa',
        when: '2022',
    },
    {
        image: '/cases/mundo/dialogo-interativo-8.png',
        project: 'Diálogo Interativo 8',
        client: 'Conferência do Oceano da ONU',
        where: 'Lisboa',
        when: '2022',
    },
    {
        image: '/cases/mundo/ocean-talks.png',
        project: 'Ocean Talks',
        client: 'Galp Energia',
        where: 'Portugal',
        when: '2019',
    },
    {
        image: '/cases/mundo/innovation-ocean.png',
        project: 'Innovathon – Ocean Edition',
        client: 'CEIIA e UN Global Compact / Sustainable Ocean Business Action Platform',
        where: 'Portugal',
        when: '2019',
    },
    {
        image: '/cases/mundo/moon-and-sun.png',
        project: 'Moon & Sun – De Volta às Origens',
        client: 'Oceans & Flow',
        where: 'Portugal',
        when: '2019',
    },
    {
        image: '/cases/mundo/campus-party.png',
        project: 'Campus Party Portugal',
        client: 'Campus Party',
        where: 'Portugal',
        when: '2020',
    },
    {
        image: '/cases/mundo/bussola.png',
        project: 'Bússola',
        client: 'SOA Hub Portugal e Sciaena',
        where: 'Portugal',
        when: '2021',
    },
    {
        image: '/cases/mundo/sofonia.png',
        project: 'LUSOFONIA – Série de Webinars',
        client: 'Ocean Hub Portugal / Sustainable Ocean Alliance',
        where: 'Portugal',
        when: '2020',
    },
    {
        image: '/cases/mundo/movimento.png',
        project: 'Movimento H2OFF',
        client: 'APDA - Associação Portuguesa de Distribuição e Drenagem de Águas',
        where: 'Portugal',
        when: '2021',
    },
    {
        image: '/cases/mundo/action-now.png',
        project: 'Action Now: percursos sustentáveis',
        client: 'Rinascita Digitale',
        where: 'Itália',
        when: '2022',
    },
    {
        image: '/cases/mundo/conversas-ao-redor.png',
        project: 'Conversas ao Redor do Fogo',
        client: 'The Nature Coaching Academy',
        where: 'Itália',
        when: '2022',
    },
    {
        image: '/cases/mundo/asia-e-africa.png',
        project: 'Ásia & África',
        client: '',
        where: 'Ásia & África',
        when: '2017-2022',
    },
    {
        image: '/cases/mundo/china.png',
        project: 'SHENZHEN OCEAN FESTIVAL',
        client: 'Mermaid Alliance / ADEX',
        where: 'China',
        when: '2017',
    },
    {
        image: '/cases/mundo/mermaid.png',
        project: 'MERMAID ISLAND ',
        client: 'Mermaid Alliance',
        where: 'Tailândia',
        when: '2017',
    },
    {
        image: '/cases/mundo/ocean-advisor.png',
        project: 'MFI Ocean Literacy Advisor',
        client: 'Mermaid Federation International (MFI)',
        where: 'Hong Kong',
        when: '2017-2022',
    },
    {
        image: '/cases/mundo/scuba-diver.png',
        project: 'SCUBA DIVER: Ocean Planet Magazine',
        client: 'Underwater 360 e MFI',
        where: 'Australasia',
        when: '2018',
    },
    {
        image: '/cases/mundo/adex-pixel.png',
        project: 'ADEX PIXEL VIRTUAL EXPO',
        client: 'ADEX ASIA',
        where: 'Cingapura',
        when: '2020-2021',
    },
    {
        image: '/cases/mundo/seagrass-underwater.png',
        project: 'SEAGRASS UNDERWATER',
        client: 'SOA Tanzania',
        where: 'Tanzânia',
        when: '-',
    },
    {
        image: '/cases/mundo/o-mar-e-sou-eu.png',
        project: 'O MAR É SOU EU',
        client: 'Conservatorium',
        where: 'Angola',
        when: '2021-2022',
    },
    {
        image: '/cases/mundo/americas.png',
        project: 'Américas (América do Norte & Hispânica)',
        client: '',
        where: 'Américas',
        when: '2020',
    },
    {
        image: '/cases/mundo/water-innovation-lab.png',
        project: 'Water Innovation Lab – WIL Global',
        client: 'Waterlution',
        where: 'Canadá',
        when: '2020',
    },
    {
        image: '/cases/mundo/beyond-boarders.png',
        project: 'Beyond Boarders: International Online Forum',
        client: 'American Lab Theatre, Theatre of Now, Culture Monks e Instabili Vaganti',
        where: 'EUA',
        when: '2020',
    },
    {
        image: '/cases/mundo/world-water-forum.png',
        project: 'World Water Forum',
        client: 'Mundial da Água, World Water Council, Governo do Brasil.',
        where: 'Brasil',
        when: '2018',
    },
    {
        image: '/cases/mundo/encontro-de-educacao.png',
        project: '1° Encuentro de Educación Marina de Latinoamerica y el Caribe',
        client: 'RELATO Oceano, The University of Edinburgh',
        where: 'Caribe',
        when: '2020',
    },
    {
        image: '/cases/mundo/soa-connects.png',
        project: 'SOA Connects – Ocean Solutions Summit',
        client: 'SOA Latinoamerica',
        where: '-',
        when: '2020',
    },
    {
        image: '/cases/mundo/unesco.png',
        project: '-',
        client: '-',
        where: '-',
        when: '2019-2030',
    },
    {
        image: '/cases/mundo/ocean-literacy-for-all.png',
        project: 'Cultura Oceânica para Todos: uma Estratégia para a Conservação, Restauração e Uso Sustentável no nosso Oceano / Desenvolvimento Profissional de Cultura Oceânica para o Setor Privado',
        client: 'COI-UNESCO',
        where: 'Veneza',
        when: '2019',
    },
    {
        image: '/cases/mundo/virtual-ocean.png',
        project: 'Virtual Ocean Literacy Summit',
        client: 'COI-UNESCO',
        where: 'Global',
        when: '2020',
    },
    {
        image: '/cases/mundo/ocean-literacy-training-course.png',
        project: 'Ocean Literacy Training Course',
        client: 'COISCO',
        where: 'Global',
        when: '2021',
    },
    {
        image: '/cases/mundo/cultura-oceanica-com-todos.png',
        project: 'Cultura Oceânica com Todos ',
        client: 'COI-UNESCO',
        where: 'Global',
        when: '2021',
    },
    {
        image: '/cases/mundo/sea-beyond.png',
        project: 'Sea Beyond – First / Second Edition',
        client: 'Grupo Prada e COI-UNESCO',
        where: 'África do Sul, Alemanha, Brasil, China, França, Itália, México, Nova York, Paris, Peru, Portugal e Reino Unido.',
        when: '-',
    },
    {
        image: '/cases/mundo/ocean&climate.png',
        project: 'Ocean & Climate Village Exhibition',
        client: 'COI-UNESCO',
        where: '-',
        when: '2022',
    },
    {
        image: '/cases/mundo/ocean-literacy-dialogo.png',
        project: 'Ocean Literacy Dialogues',
        client: 'COI-UNESCO, Comissão Europeia e Coalisão EU4Ocean.',
        where: '-',
        when: '2022',
    },

    
];